version: '3.1'
services:
    memcached:
        image: 'memcached:alpine'
        container_name: memcached

    redis:
        image: 'redis:alpine'
        container_name: redis

    #  mariadb:
    #     image: 'mariadb:10.6'
    #     container_name: mariadb
    #     restart: unless-stopped
    #     working_dir: /var/www
    #     volumes:
    #         - ./docker/mariadb:/var/lib/mariadb
    #     environment:
    #         - MYSQL_ROOT_PASSWORD=root
    #         - MYSQL_DATABASE=database_name
    #         - MYSQL_USER=database_username
    #         - MYSQL_PASSWORD=database_password
    #     ports:
    #         - '8081:3306'
    
    mysql:
        image: 'mysql:8.0'
        container_name: mysql
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - ./db/mysql:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=database_name
            - MYSQL_USER=database_username
            - MYSQL_PASSWORD=database_password
        ports:
            - '8081:3306'

    elasticsearch:
        image: 'elasticsearch:6.5.4'
        container_name: elasticsearch

    webserver:
        image: 'nginx:alpine'
        container_name: nginx
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - './src:/var/www'
            - './docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
        ports:
            - '8080:80'

    php-fpm:
        build: docker/php-fpm
        container_name: php
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - './src:/var/www'
            - './docker/php-fpm/php-ini-overrides.ini:/etc/php/8.0/fpm/conf.d/99-overrides.ini'
