version: '3.1'
services:

    mariadb:
        image: 'mariadb:10.6'
        container_name: mariadb
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - ./db/mariadb:/var/lib/mariadb
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=database_name
            - MYSQL_USER=database_username
            - MYSQL_PASSWORD=database_password
        ports:
            - '8081:3306'

    webserver:
        image: 'nginx:alpine'
        container_name: nginx
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - './src:/var/www'
            - './docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
        ports:
            - '8080:80'

    php-fpm:
        build: docker/php-fpm
        container_name: app
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - './src:/var/www'
            - './docker/php-fpm/php-ini-overrides.ini:/etc/php/8.0/fpm/conf.d/99-overrides.ini'
