version: '3.3'
services:

    webserver:
        image: 'nginx:alpine'
        container_name: nginx
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - './src:/var/www'
            - './docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
        links:
            - mysql
        networks:
            - frontend
            - backend
        ports:
            - '8000:80'

    php-fpm:
        build: docker/php-fpm
        container_name: app
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - './src:/var/www'
            - './docker/php-fpm/php-ini-overrides.ini:/etc/php/8.0/fpm/conf.d/99-overrides.ini'
        networks:
            - frontend
            - backend

    mysql:
        platform: linux/x86_64
        image: 'mariadb:latest'
        container_name: mysql
        restart: always
        working_dir: /var/www
        volumes:
            - ./docker/mariadb:/var/lib/mariadb
        environment:
            MYSQL_ROOT_PASSWORD: pwd
        networks:
            - backend
        ports:
            - '3306:3306'
    
    adminer:
        image: adminer
        restart: always
        networks:
            - backend
        ports:
            - 8005:8080

networks:
  frontend:
    external: true
    driver: driver-frontend
  backend:
    external: true
    driver: driver-backend